### ISSUE TITLE
Could quickfix list use the actual files instead of the virtual_includes symlinks?

### ISSUE THREAD

**Issue by rnburn** [lakshayg/vim-bazel#3]
When I run `:Bazel build //...` and go through the quickfix list for errors, the files are the symlinks that bazel sets up rather than the original files, which makes them inconvenient to work with.

If the error from bazel points to a symlink, is it possible to use the original file in the quickfix list?

**Comment by lakshayg** [comment]
I don't have this problem in my local setup. Maybe I'm not understanding your issue properly. Could you please share a reproducible example?

I already have some logic in the plugin to resolve symlinks: https://github.com/lakshayg/vim-bazel/blob/master/autoload/bazel.vim#L11-L15

**Comment by rnburn** [comment]
I can try to put together a small example that reproduces, but here's why my setup looks like:

My project is layed out like

```
WORKSPACE
src/dir1/subdir1/BUILD
src/dir1/subdir1/src1.h
src/dir1/subdir1/src1.cc
...
```

where `BUILD` has an entry like

```
cc_library(
  name = "mylib"
  hdrs = ["src1.h"],
  srcs = ["src1.cc"],
  include_prefix = "dir1/subdir1",
)
```

Suppose my vim working dir is the project root and src1.h is not open but has a change that will result in a build failure.

If I run `Bazel build //....`, then vim will open to the build file but the quickfix list is populated with entries like this

```
src/dir1/subdir1/BUILD|18 col 19 error| Compiling src/dir1/subdir1/src1.cc failed: (Exit 1): proj_cc_wrapper failed: error executing command /home/rnburn/.cache/bazel/_bazel_rnburn/5cc66d25042c64a0db4adf3af688e930/external/local_config_cc/extra_tools/proj_cc_wrapper -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign ... (remaining 122 argument(s) skipped)
bazel-out/k8-fastbuild/bin/src/dir1/subdir1/_virtual_includes/src1/dir1/subdir1/src1.h|13 col 25 error| no template named 'abc'
```

And if I move through the quickfix list to the file it opens to `bazel-out/k8-fastbuild/bin/src/dir1/subdir1/_virtual_includes/src1/dir1/subdir1/src1.h` rather than `src/dir1/subdir1/src1.h`

**Comment by lakshayg** [comment]
I'm using this project: https://github.com/lakshayg/tmp-bazel-issue and here's the error I get:

```
src/dir1/subdir1/BUILD|1 col 11 error| Compiling src/dir1/subdir1/src1.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' ... (remaining 21 argument(s) skipped)
|| 
|| Use --sandbox_debug to see verbose messages from the sandbox
src/dir1/subdir1/src1.cc|7 col 39 error| too few template arguments for class template 'SizeOf'
||   std::cout << "sizeof(string) = " << SizeOf<std::string>::value << '\n';
||                                       ^
src/dir1/subdir1/src1.h|2 col 8| template is declared here
|| struct SizeOf {
||        ^
|| 1 error generated.
|| Target //src/dir1/subdir1:mylib failed to build
|| Use --verbose_failures to see the command lines of failed build steps.
|| INFO: Elapsed time: 0.817s, Critical Path: 0.44s
|| INFO: 6 processes: 6 internal.
|| FAILED: Build did NOT complete successfully
|| FAILED: Build did NOT complete successfully
```

Could you create a minimal project where you encounter this issue?

**Comment by rnburn** [comment]
I put in a PR to the example. There were some details I missed in my description.

But if you run the PR version, the quickfix list has the entry 
```
bazel-out/k8-fastbuild/bin/src/dir1/subdir1/_virtual_includes/mylib/dir1/subdir1/src1.h
``` 
for the header file.

**Comment by lakshayg** [comment]
As discussed in the example project, removing `include_prefix` from the build target resolves the issue without any  changes to the plugin. Closing this issue. Feel free to reopen if there are cases where removing `include_prefix` is not acceptable.
